### ISSUE TITLE
Heroku/Glitch error

### ISSUE THREAD

**Issue by BjornGrylls** [barbarbar338/terraria-server#1]
I get the following errors when trying to build the server on Heroku
![image](https://user-images.githubusercontent.com/35100000/101929373-0c948700-3bd7-11eb-9114-823d5dfe5a0d.png)
Both run "ts-node src --build" which apparently is not found. I have run "npm install" before that

Glitch also fails on the same command.

**Comment by barbarbar338** [comment]
Try adding `ts-node` to dependencies
if you want you can create a pull request about it :)
if you don't, i will update repo probably in 40-45 mins

**Comment by BjornGrylls** [comment]
I just copied all the devDependencies into dependencies, which works. But you should probably update it because you know what the different dependencies are used for.

I now got a new error which I will make a new issue for.

**Comment by barbarbar338** [comment]
I'm trying to fix it now
