### ISSUE TITLE
Can't start on Heroku or Glitch

### ISSUE THREAD

**Issue by BjornGrylls** [barbarbar338/terraria-server#4]
I was so happy Sunday morning when I saw you had comitted a fix for the previous issues. Unfortunately it still doesn't work on Heroku nor Glitch.
I have made some changes in my fork so it can be run on Linux too, like the `chmod -R 777 server/` (should probably be changed to `chmod -R -x server/` or something). After spending the last couple days both now get stuck at this error:

![image](https://user-images.githubusercontent.com/35100000/102200937-c33d8380-3ec5-11eb-8741-3aefa71b354e.png)

I've tried using the Heroku container ([https://github.com/BjornGrylls/docker.terraria-server-vanilla](url)) and had the same problem then. The fix at that time was to change the line endings in the script file from CRLF (Windows) to LF (Linux). This is hovever not possible with the TerrariaServer.exe since I don't have access to the source code. The strange part is that the same TerrariaServer.exe worked in the Heroku container. The container only supports http, which means I can't connect to the server, so I'm back at trying to get the NodeJS working.

I've run out of ideas and hope you can help with this.

**Comment by barbarbar338** [comment]
First of all thanks for your PR
I've merged your PR and I'm looking for a solution to the error.

**Comment by barbarbar338** [comment]
It works when I open the server with a ".bin.x86_64" extension instead of ".exe" file but I seem to do a few edits about the server config file because it doesn't detect the configs :D I'll commit a bug fix in a few seconds
